### ISSUE TITLE
Fatal Error C1083

### ISSUE THREAD

**Issue by karbonog** [nickcano/XenoScan#2]
![error](https://user-images.githubusercontent.com/29764580/27675632-aaf2a4dc-5c5f-11e7-967d-1ca56aaaa6c0.png)
I am trying to build the project in visual studio but get this error. Does anyone know why this is happening and do we have a possible fix? 

Thank you! :D

**Comment by nickcano** [comment]
Are you compiling on the same version of Visual Studio (I'm using 2010 iirc)? If not, you may have different library versions (or project settings).Here's one way you might track the issue down. In the project settings for XenoScanEngine, you can set a flag to show the include tree in the output window. Set that flag, then check the output and find out what's leading to "corecrt.h" being included. Once you know, remove that include.That should generate a new set of errors, hopefully telling you some definitions are missing. You can then search around on Google or some documentation to find what libs need to be included in your situation. You can then share that info with me and I can incorporate a mutual fix.I'd be happy to do this myself, but I'd need detailed information on order to attempt a reproduction on my end.On Jun 29, 2017 12:14 AM, karbonog <notifications@github.com> wrote:
I am trying to build the project in visual studio but get this error. Does anyone know why this is happening and do we have a possible fix?
Thank you! :D

**Comment by karbonog** [comment]
![error 1](https://user-images.githubusercontent.com/29764580/27726682-416988a6-5d30-11e7-88a7-f33b65f4aaa1.png)
I was using Visual Studio 2015 tried to get it to run with it but just couldn't quite get there(I think its a compatibility issue not necessarily the code itself) I will keep trying to get it and post the fix. But in order to get the program running i downloaded the 2010 version, and now i get this error. Not sure how to fix this as i'm new to visual studio so this is all quite foreign to me. 
P.S. thank you for the prompt response!
Thanks again!

**Comment by nickcano** [comment]
Are you trying to use the project from a clean repo on 2010? Or are you using the same working directory as you were for 2015 without a 'git reset --hard HEAD' ? It's likely that 2015 screwed up your project configuration, leading to the project getting choked on in 2010.On Jun 30, 2017 1:08 AM, karbonog <notifications@github.com> wrote:
I was using Visual Studio 2015 tried to get it to run with it but just couldn't quite get there(I think its a compatibility issue not necessarily the code itself) I will keep trying to get it and post the fix. But in order to get the program running i downloaded the 2010 version, and now i get this error. Not sure how to fix this as i'm new to visual studio so this is all quite foreign to me.
P.S. thank you for the prompt response!
Thanks again!

**Comment by karbonog** [comment]
Thanks again for the quick response! As for the 'git reset --hard Head' i'm not exactly what that command is or how to go about executing it.

**Comment by nickcano** [comment]
You need to run that from your git command prompt, or, if you're using a GUI, find the matching button. If you're not using git, you may want to take a step back and learn to use it properly, it will make your life easier. If you're not using it and you insist, though, you'll need to re download the source tree so everything is fresh.On Jun 30, 2017 2:04 AM, karbonog <notifications@github.com> wrote:Thanks again for the quick response! As for the 'git reset --hard Head' i'm not exactly what that command is or how to go about executing it.

**Comment by karbonog** [comment]
Okay thank you for the advice, ill take the time and learn Git. But downloading a fresh file allowed it to build in 2010. Thank you for your help! It is much appreciated.

**Comment by nickcano** [comment]
I've updated the code to be more friendly to other environments. For Visual Studio 2015, your build process should look something like this:

PREREQUISITES:
- Some version of Visual Studio >= 2010
- git bash
- CMake

First, checkout the code from a git-enabled command prompt:
```
git clone --recursive https://github.com/nickcano/XenoScan.git
```

Next, open the Visual Studio Command Prompt (*Start Menu -> Search -> "Visual Studio Command Prompt" -> Select either x86 or 32bit*) and do:
```
cd C:\path\to\XenoScan
buildmsvc2015.bat
```

Now, inside of the `XenoScan` folder, you should see a folder named `build`.  Inside of this folder, you should see `XenoScan.sln`, which is what you'll open in Visual Studio.

If the process works as designed, it should compile LuaJIT for you, as well as generate a project which should compile seamlessly.
